#index:
#    path: /
#    controller: App\Controller\DefaultController::index
HomePage:
    path: /
    controller: App\Controller\HomeController::index
Contact:
    path: /contact
    controller: App\Controller\PageController::contact
Projet:
    path: /projet/{projet}
    controller: App\Controller\PageController::projet


