
services:
  app.home.controller:
    class: Tws\Controller\HomeController

  app.page.controller:
    class: Tws\Controller\PageController

  app.dessin.controller:
    class: Tws\Controller\Dessincontroller